- scripts/protect-branches.py
re #2043
https://pulp.plan.io/issues/2043
> adding a script to set github branches as protected

- scripts/dev-setup.sh
> Fix the dev-setup.sh script to be aware of the new devel repo.

- Vagrantfile.example
I've documented the necessary setup here: https://github.com/pulp/pulp/pull/2754
> Update the Vagrant.example file to use SSHFS

- ansible/roles/dev/files/bashrc
- ansible/roles/dev/files/drop_database.js
- ansible/roles/dev/files/motd
- ansible/roles/dev/tasks/main.yml
fixes #2194
https://pulp.plan.io/issues/2194
> Update bash aliases to work better with pulp 3/django

- scripts/checkout.py
Here is some basic usage:
python checkout.py --version master
> Adds a script to checkout Pulp by version

- ansible/library/pulp_facts.py
Solution: replace python-lxml with python2-lxml when gathering pulp facts
> Problem: ansible is unable to install python-lxml

- Vagrantfile.example
> Fixed a missing space throwing off the formatting

- ansible/roles/dev/files/motd
Signed-off-by: Abhijeet Kasurde <akasurde@redhat.com>
> Fix motd link for pulp-devel guide

- ansible/roles/dev/tasks/main.yml
- ansible/roles/vagrant/templates/bashrc.j2
re #2479
https://pulp.plan.io/issues/2479
> Ansible deploy pulp3 systemd services

- scripts/mention-bot.py
closes #2442
https://pulp.plan.io/issues/2442
> Add mention-bot script to update mentionbot configs in pulp repos

- ansible/library/pulp_facts.py
- ansible/roles/dev/tasks/main.yml
- ansible/roles/dev/templates/pulp_celerybeat.j2
- ansible/roles/dev/templates/pulp_resource_manager.j2
- ansible/roles/dev/templates/pulp_worker@.j2
Intended to be merged at the same time as https://github.com/pulp/pulp/pull/3003
https://pulp.plan.io/issues/2742
> Developer install of plugins, platform, and deps into (pulp) venv

- ansible/roles/dev/tasks/main.yml
- ansible/roles/dev/templates/pulp_celerybeat.j2
- ansible/roles/dev/templates/pulp_resource_manager.j2
- ansible/roles/dev/templates/pulp_worker@.j2
- ansible/roles/vagrant/templates/bashrc.j2
ref #2444
https://pulp.plan.io/issues/2444
> Update vagrant to use refactored pulp package names

- ansible/roles/dev/tasks/main.yml
re #2416
https://pulp.plan.io/issues/2416
> Copy server.yaml into correct location, generate django secret_key

- Vagrantfile.example
- ansible/dev-playbook.yml
- ansible/kombu-playbook.yml
- ansible/vagrant-playbook.yml
https://pulp.plan.io/issues/2829
> Avoid collisions with Pulp 3 dev env

- Vagrantfile.example
- ansible/example-playbook.yml
https://pulp.plan.io/issues/2829
> Avoid collision with Pulp2 dev env

- ansible/roles/dev/tasks/main.yml
re #2842
https://pulp.plan.io/issues/2842
> Update location of etc/pulp/server.yaml

- scripts/checkout.py
This cherry picks the checkout script from master to the 3.0-dev branch.
> Add checkout to 3.0

- ansible/roles/pulp-user/tasks/main.yml
It's usually better to use a module than an arbitrary command.
> Use getent module instead of getent command

- ansible/deploy-pulp3.yml
- ansible/requirements.yml
closes #2840
https://pulp.plan.io/issues/2840
> Publish ansible galaxy playbook for pulp3 pypi installation.

- ansible/roles/dev/tasks/main.yml
Solution: extend the dev role to create both directories
> Problem: /var/lib/pulp and /var/lib/pulp/tmp missing

- scripts/checkout.py
Renaming pulp_packaging to pulp-ci
> Renaming pulp_packaging to pulp-ci

- ansible/roles/dev/tasks/main.yml
**DO NOT MERGED UNTIL 2017-11-13.**
refs #3089
https://pulp.plan.io/issues/3089
> Updating for move of platform/ to pulpcore/

- Vagrantfile.example
- ansible/roles/db/tasks/main.yml
- ansible/roles/dev/files/venv.bashrc
- ansible/roles/dev/tasks/main.yml
Trying my own Pulp3 dev deployment I hit some issues.
This is my attempt to fix those in an unsorted manner.
> Cleaning up the Docker provider path

- Vagrantfile.example
- ansible/roles/pulp-certs/tasks/main.yml
Change the vagrant box type to Fedora 27. Also made it
easier to use sshfs as the folder sync method.
> Update development box

- ansible/roles/dev/tasks/main.yml
- ansible/roles/pulp/defaults/main.yaml
- scripts/vagrant-setup.sh
Added selinux utilities to set of preinstalled tools.
Updated the pulp-smash settings config file.
> Updated dev environment

- ansible/roles/pulp-user/tasks/main.yml
No custom facts are gathered, so don't install a package for gathering
custom facts.
> Don't install unnecessary package

- ansible/roles/systemd/tasks/main.yml
ref #3406
https://pulp.plan.io/issues/3406
Requires: https://github.com/pulp/pulp/pull/3370
> Drop creation of the /var/cache/pulp directory

- ansible/deploy-pulp3.yml
Changes were made in https://github.com/pulp/ansible-pulp3/pull/6
Mainly the 4 ansible roles have been smooshed into one big role.
> Modify playbook to account for ansible role changes

- Vagrantfile.example
Also increase the allocated RAM, because 2gb is not enough.
> Switch to sshfs for shared folders default

- Vagrantfile.example
- ansible/library/pulp_facts.py
This has been blocked for a while due to build infrastructure issues.  They are fixed now, so we can move forwards.
> Bump Fedora version to 28

- .travis.yml
- ansible/pulp-from-source.yml
- ansible/roles/dev_tools/tasks/main.yml
> Misc updates

- Vagrantfile.example
- ansible/roles/pulp-user/files/netrc
Since this is a real domain, it causes problems.
A rebase and update of https://github.com/pulp/devel/pull/144
> Do not use "dev" domain

- Vagrantfile.example
- ansible/roles/plugin/default/main.yaml
- ansible/roles/plugin/tasks/install_plugin.yml
> Install test_requirements in development box

- ansible/roles/dev/tasks/main.yml
ref #4067
https://pulp.plan.io/issues/4067
> Updating devel to use new pulpcore-plugin repo

- ansible/roles/dev/tasks/main.yml
> Fix paths to pulpcore package and settings

- ansible/roles/dev/tasks/main.yml
- ansible/roles/pulp-user/templates/alias.bashrc
- ansible/roles/systemd/tasks/main.yml
- ansible/roles/systemd/templates/pulp_content_app.j2
Add the systemd service file, add pulp_content_app to bash helpers and
configure pulp to redirect to the content app.
https://pulp.plan.io/issues/4239
re #4239
> Add content app service

- Vagrantfile.example
- ansible/roles/plugin/tasks/main.yml
Updating the box type to Fedora 29
Increasing the RAM allocation from 2gb to 4gb
> Update to Fedora 29

- ansible/roles/django_db/tasks/main.yml
- ansible/roles/django_db/vars/main.yaml
- ansible/roles/systemd/templates/pulp_content_app.j2
> Add content app to pulp_services in django_db

- ansible/roles/dev/tasks/main.yml
- ansible/roles/dev/templates/settings.py.j2
After deleting that file in pulpcore, it needs to generated by other means.
[noissue]
> Generate settings.py from template

- ansible/roles/plugin/tasks/main.yml
- ansible/roles/pulp-user/templates/alias.bashrc
re #4279
https://pulp.plan.io/issues/4279
Required PR: https://github.com/pulp/pulp_file/pull/157
> Fix plugins installation due to the app label change

- ansible/roles/django_db/vars/main.yaml
- ansible/roles/pulp-user/templates/alias.bashrc
- ansible/roles/systemd/tasks/main.yml
- ansible/roles/systemd/templates/pulp-content-app.j2
- ansible/roles/systemd/templates/pulp-resource-manager.j2
- ansible/roles/systemd/templates/pulp-worker@.j2
closes #4187
https://pulp.plan.io/issues/4187
> Use hyphens for Pulp3' system units name.

- ansible/roles/dev/tasks/main.yml
> Move pulp to pulpcore

- ansible/roles/dev/tasks/main.yml
- ansible/roles/pulp-user/templates/alias.bashrc
re #4415
https://pulp.plan.io/issues/4415
Required PR: https://github.com/pulp/pulp/pull/3880
> Update app label for core

- ansible/roles/dev/tasks/main.yml
- ansible/roles/django_db/tasks/main.yml
- ansible/roles/plugin/tasks/install_plugin.yml
- ansible/roles/pulp-user/templates/alias.bashrc
> Use django-admin since pulp-manager has been removed

- ansible/pulp-from-source.yml
[noissue]
@daviddavis seems like this is also needed.
> Add DJANGO_SETTINGS_MODULE to playbook

- README.md
fixes #4587
https://pulp.plan.io/issues/4587
> Add note about this being only for Pulp 2
