pulp/devel

ansible/roles/core/tasks/main.yml
If selinux-policy package is not installed, rpmspec produces spurious
requirements for packages named "selinux-policy", "is", "not", "installed"
which breaks subsequent ansible tasks.  This is due to the macro in
pulp.spec:
%define selinux_policyver %(rpm --qf "%%{version}-%%{release}" -q %%selinux-policy)
We know we'll need this package anyway, so just install it a bit
earlier to fix this.
=> ansible: fix pulp_facts when selinux-policy not installed

ansible/library/pulp_facts.py, ansible/roles/core/tasks/main.yml
In 3.0-dev branches, the spec files have been removed from the project
repositories. Ansible needs to look in the packaging repository to
gather the list of dependencies.
=> Ansible now looks for the pulp/packaging repo for specs

ansible/dev-playbook.yml, ansible/roles/lazy/files/squid-3.1.conf, ansible/roles/lazy/tasks/main.yml, ansible/roles/pulp-certs/tasks/main.yml, ansible/roles/pulp-coverage/defaults/main.yaml, ansible/roles/pulp-coverage/tasks/install.yaml, ansible/roles/pulp-coverage/tasks/main.yaml, ansible/roles/pulp-coverage/tasks/report.yaml, ansible/roles/pulp-coverage/tasks/uninstall.yaml, ansible/roles/pulp-smash/defaults/main.yml, ansible/roles/pulp-smash/tasks/main.yaml, ansible/roles/pulp-smash/templates/settings.j2, ansible/roles/pulp/defaults/main.yaml, ansible/roles/pulp/handlers/main.yaml, ansible/roles/pulp/tasks/main.yaml, ansible/roles/pulp/tasks/pulp_server.yaml, ansible/roles/pulp/templates/yum_repo.j2, ansible/vagrant-playbook.yml
I went with the pulp_packaging version of the ``lazy`` and ``pulp-certs`` roles, which are more general. I didn't attempt to de-duplicate anything beyond those overlapping roles, but this will at least have us all working in the same repository for Ansible.
=> Merge pulp_packaging Ansible roles and playbooks

ansible/roles/dev/files/bashrc
The worker python modules are moved into pulp.tasking now.
=> Updates bashrc for new worker layout

ansible/roles/lazy/tasks/main.yml
This is so plugins are loaded into the streamer.
closes #2272
https://pulp.plan.io/issues/2272
=> Starts pulp_streamer with other pulp services

ansible/roles/lazy/tasks/main.yml, scripts/vagrant-setup.sh
Services are already started by ansible, it make sense to do a prestart instead of a pstart on vagrant setup.
=> Restart services on vagrant-setup

ansible/kombu-playbook.yml, ansible/roles/kombu/tasks/main.yaml
I hack on kombu in the Vagrant environment, but the
default install is rpm based.
This little playbook converts the kombu installation
to a developer checkout in ~/devel/kombu
=> Adds a kombu developer playbook

ansible/roles/kombu/tasks/main.yaml
If errors occur when the command to uninstall
python-kombu with --nodeps occurs, the easiest+best
thing to do is ignore them.
=> Improves kombu playbook error handling

ansible/roles/dev/tasks/main.yml
Solution: Stop checking version of Fedora running on the dev machine when
deciding whether or not to enable the upstream repositories
closes #2489
https://pulp.plan.io/issues/2489
=> Problem: upstream Pulp repositories not enabled on Vagrant box

ansible/roles/dev/tasks/main.yml
Solution: expand the dev role to install gofer package
closes #2465
https://pulp.plan.io/issues/2465
=> Problem: gofer package not installed on Vagrant box

scripts/checkout.py
Previously the checkout script required 'version' to be set.
This change sets 'master' as the default value for 'version'.
Running the following will now check out master.
python scripts/checkout.py
=> Checkout script uses master by default

Vagrantfile.example
Solution: This patch ensures that the guest VM spawned by vagrant uses the 'host-passthrough'
CPU mode. In this mode, the CPU visible to the guest should be exactly the same as the host
CPU even in the aspects that libvirt does not understand[0]. This patch was inspired by a
workaround proposed in a related BZ[1].
[0] https://libvirt.org/formatdomain.html#elementsCPU
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1283989
=> Problem: vagrant box fails to obtain IP

.gitignore
To help avoid people accidentally including their personal vagrant setup in a commit
=> Ignore the user-specific Vagrantfile and .vagrant directory

Vagrantfile.example
Bring the major Fedora version used for docker in-line with the version
used with libvirt.  Both vagrant providers should be using the same base.
=> Vagrant: bump Fedora version when using docker

Vagrantfile.example
Tested this just now. We've already made this change on 3.0-dev, but we (really, I...) didn't bring that change to master, which is still on fedora 24. I just vagrant up'd with this and ran all tests, everything seems fine (which, again, was our experience on 3.0-dev).
Thanks to @rohanpm for pointing out this oversight in #29.
=> Update Vagrant example to f25

ansible/roles/dev/tasks/main.yml, ansible/roles/lazy/tasks/main.yml
This fix requires https://github.com/pulp/pulp/pull/2959 to be merged first
closes #2497
https://pulp.plan.io/issues/2497
=> Vagrant stops installing pulp-server rpm

.gitignore, Vagrantfile.example, ansible/library/pulp_facts.py
- Example Vagrantfile updated with changes from pulp 2
- modified the gitignore to ignore different Vagrantfiles and
all playbook retry files from ansible.
- Playbook updated to use the dev_requirements file intoduced in
https://github.com/pulp/pulp/pull/2888
=> Provisioning updates for Pulp 3

ansible/library/pulp_facts.py, ansible/roles/dev/tasks/main.yml
I'm been digging into figuring out why the platform virtualenv appeared
to be getting set up improperly, and had started down a scary path of
redoing how those virtualenvs get created. Then Austin asked me if the
'- plugin' item was left out of the platform virtualenv setup on
purpose. I'd just noticed that too, and discovered that this was the
actual cause of the virtualenv problems and I'd just missed it. Woot.
I was able to steal some of the virtualenv work I was doing, though, and
make the playbook also install pulp_file into the platform virtualenv if
the repo's cloned into the devel dir when the playbook runs, so that's
cool too.
=> Platform virtualenv installs pulp_file

ansible/roles/dev/tasks/main.yml
A pulp-smash dependency (editdistance) has recently changed, and now requires c++ support in gcc for its binary components to successfully install.
=> Install gcc-c++ in dev environment

ansible/roles/kombu/tasks/main.yaml
Without this reordering if you run the playbook without having Kombu
cloned locally your Pulp installation will be broken. By reordering this
all of the checking happens up front which should allow your Pulp
environment to still be working regardless of if the playbook passes or
fails.
=> Reorder the kombu ansible playbook

ansible/library/pulp_facts.py
Provisioning fails, if python-lxml is not in rpm_dependency_list.
This version replaces python-lxml silently and does nothing if it is not found.
If you dislike list comprehensions, i can provide another version.
=> Fix replacing python-lxml if not on rpm_dependency_list

ansible/roles/vagrant/templates/bashrc.j2
https://docs.djangoproject.com/en/1.8/topics/migrations/#dependencies
Django can't create a test database without schema generation of auth. See this comment for more detail. https://github.com/pulp/pulp/blob/b86677f069c03643380d98bc51cd1291fdfa3289/platform/pulp/app/db-reset.sh#L18-L24
=> fix ptest - Migrate auth because User depends on it

ansible/roles/dev/tasks/main.yml
Since Django is installed in a virtual environment, it should should be
activated before manage.py commands are run.
The order is changed because Django is installed as a dependency of platform and must be installed to migrate.
closes #2708
Depends on https://github.com/pulp/pulp/pull/3022 being merged first.
=> Pass virtualenv to db-reset

ansible/roles/common/files/netrc, ansible/roles/common/tasks/main.yml, ansible/roles/common/templates/alias.bashrc
This will allow us to make calls via httpie without having to supply credentials every time. More info:
https://github.com/jakubroztocil/httpie#netrc
Before:
```
http --auth admin:admin :3000/api/v3/repositories/
```
After:
```
http :3000/api/v3/repositories/
```
Note that you can still override credentials by setting `--auth`.
=> Add netrc file to store admin credentials

scripts/checkout.py
I'm on centos 7 and the latest version of python in epel7 is python 3.4 (see https://dl.fedoraproject.org/pub/epel/7/x86_64/p/). The `subprocess.run()` is python 3.5+ only. 
I'm happy to close this out though if we decide we don't want to support python 3.4.
=> Support Python 3.4 in checkout.py

scripts/checkout.py
The base-dir option allows the checkout.py script to operate on a pulp
checkout anywhere on the filesystem.
(cherry picked from commit f024edc5f036834802006d74277e34f83c37db92)
=> Adds base-dir option

ansible/example-playbook.yml, ansible/group_vars/all, ansible/roles/dev/defaults/main.yml, ansible/roles/dev/tasks/main.yml
The `pip_install_extras` variable is mentioned in three places:
1. It's used by the `dev` role. By default, the variable is undefined,
so the reference to this variable must account for this with an `if
pip_install_extras is defined ...`.
2. It's set to `false` for group "all."
3. It's set to `true` by `example-playbook.yml`. (Note that the playbook
only applies to hosts in group "pulp3_dev.")
This is a bit complicated for a variable that's used exactly once.
Simplify things by giving this variable a default value.
This has the down-side of making this variable less obvious. However,
the proper fix is to document this variable in the site-wide readme or
`roles/dev/README.md`, instead of spamming the code base with this
variable. No formal documentation is added by this commit.
As a side …
=> Simplify variable usage

ansible/roles/common/tasks/main.yml
Bash processes input in a pipelined fashion. In order, several of the
steps are:
1. Variable expansion.
2. Command substitution.
3. Word splitting.
4. Globbing.
Therefore:
* Variables should be quoted.
* It is safe to perform globbing without worrying about word splitting.
The point about globbing may seem non-obvious. Here's an example:
```console
$ touch 'one two' three
$ ls -1
'one two'
three
$ for file in $(/bin/ls .); do echo "$file"; done
one
two
three
$ for file in ./*; do echo "$file"; done
./one two
./three
```
=> Fix weakness in bash script

ansible/library/pulp_facts.py
Don't create a variable with the same name as its enclosing function.
There's no good reason to shadow names like this.
Rewrite the comments at the head of the function, and turn them into a
docstring.
Rewrite the logic that asserts that the source code for the Pulp
platform is present.
=> Rewrite function for finding Pulp source code dirs

Vagrantfile.example, ansible/pulp-from-source.yml
Rename playbook from `example-playbook.yml` to `pulp-from-source.yml`.
Hopefully, this makes this playbook's effects more obvious: when run, it
will install Pulp from source. This also sets up a more obvious naming
scheme for future playbooks, such as `pulp-from-pypi.yml`.
=> Rename playbook for installing Pulp from source

ansible/pulp-from-source.yml
The default value for `become_method` is "sudo." Don't re-declare this
option in the `pulp-from-source.yml` playbook. It's acts as unnecessary
noise that distracts readers from more interesting code.
=> Drop unnecessary directive from Ansible playbook

ansible/roles/reset_db/tasks/main.yml
The `reset_db` role executes a script called `db-reset.sh`. If Pulp is
installed from PyPI or directly from git, then it won't exist in the
Pulp user's ~/devel/pulp directory. But no matter what type of
installation, it should exist in the virtualenv into which Pulp 3 is
installed.
Update the `reset_db` role so that it can find the `db-reset.sh` script
regardless of how Pulp 3 was installed.
=> Make reset_db role more flexible

ansible/library/pulp_facts.py
When run by Ansible, `library/pulp_facts.py` exports a fact called
`pulp_available_repositories`. This fact is a list of all of the
directories in the ~/devel/ directory. When the fact-gathering code in
this module is executed, if the `pulp` directory is absent from
`pulp_available_repositories`, an exception is thrown. The idea is that
one can't install Pulp if this source code is missing.
This is problematic for two reasons.
First, this check is redundant. The `dev` role already asserts that
"pulp" is in `pulp_available_repositories`.
Second, this check makes the existing Ansible code more inflexible. What
if one wants to install Pulp not from locally available source code, but
directly from source code on GitHub, or from packages on PyPI? By
complaining about missing source code during …
=> Drop assertion from fact-gathering code

ansible/roles/reset_db/tasks/main.yml
Reverts pulp/devel#87
The change fixed the pip/git installations, but broke "--editable" python installs (pip -e, setup.py develop). It turns out that the `*.egg-link` files created in dev installs aren't real symlinks, so this pattern won't work on dev installs.
=> Revert "Make reset_db role more flexible"

ansible/roles/dev/tasks/main.yml, ansible/roles/plugins/tasks/main.yml, ansible/roles/smash/tasks/main.yml
Python 3.3 and newer ships with the "venv" module, which is capable of
creating and managing virtualenvs. The virtualenv executable is only
needed if using an older version of Python.
Use `python -m venv` when creating virtualenvs. This drops the
dependency on the virtualenv executable. (And whatever packages provide
that executable.) Deployments of Pulp 3 will be faster and
more reliable if they use code that ships with the standard library
instead of third-party packages.
=> Drop dependency on virtualenv executable

ansible/library/pulp_facts.py, ansible/roles/dev/tasks/main.yml
`library/pulp_facts.py` currently has a function that sets a fact named
`pulp_selinux_enforcing`. This fact tells whether SELinux is in the
"enforcing" state or not.
Don't bother doing this. It's pointless. It doesn't help the "selinux"
module do its job. It pollutes the facts namespace with an extra
variable. It's yet more code to maintain. In short, it's a liability.
Also, drop some unused imports.
=> Simplify SELinux management code

ansible/deploy-pulp3.yml
The systemd role will run as the last one, to be able to pick up
the rabbitmq config and not initiating with the celery default settings.
=> Swap the rabbitmq and systemd roles.

ansible/deploy-pulp3.yml, ansible/roles/pulp-user/tasks/main.yml
Ansible lets one create a virtualenv and install a package into it with
the `pip` module. Here's an example usage:
```yaml
- hosts: all
tasks:
- name: create virtualenv
pip:
name: flake8
virtualenv: /tmp/test-venv
```
This works so long as the target hosts have Python 2 and the virtualenv
executable installed. Python 2 and virtualenv are required even when the
Ansible python interpreter is set to Python 3:
```yaml
- hosts: all
vars:
ansible_python_interpreter: /usr/bin/python3
tasks:
- name: create virtualenv
pip:
name: flake8
virtualenv: /tmp/test-venv
```
In both of these cases, a missing dependency will throw an error stating
"Failed to find required executable virtualenv in paths: …". This makes
little sense in Pulp 3's case, as it requires Python 3. Why should the
installer for Pulp …
=> Require Ansible 2.3.2+

ansible/roles/django_db/tasks/reset.yml, ansible/roles/pulp-user/templates/alias.bashrc
We removed the db-reset.sh script from pulp which called reset-admin-password. Adding in that functionality here so that we don't have to manually call it after we `vagrant up` or `pclean`.
=> Set the admin password after migrating the db

ansible/roles/dev/tasks/main.yml
Despite pinning the version of DRF https://github.com/pulp/pulp/pull/3185, we ended up with a different version because the requirements are installed in the wrong order.
=> install platform and requirements before extras

.gitignore, Vagrantfile.example, ansible/pulp-from-source.yml, ansible/roles/broker/tasks/main.yml, ansible/roles/dev/tasks/main.yml, ansible/roles/kombu_fixup/tasks/main.yml
Adds a new role called kombu_fixup which provides a source install of
qpid-tools and kombu.
closes #2259
=> Switches dev env to qpid

Vagrantfile.example, ansible/roles/lazy/tasks/main.yml, ansible/roles/pulp-certs/tasks/main.yml
mod_ssl supports a slightly older z-release of httpd, so state=latest dnf creates an unresolvable conflict
=> Fix issue on Fedora 26

ansible/pulp-from-source.yml
The dev installer currently only targets hosts in the group `pulp3_dev`.
This requirement is inexplicable and annoying. It's inexplicable because
there is no hosts file. This is annoying because it prevents users from
easily using the playbook, such as like this:
ansible-playbook pulp-from-source.yml -i fedora-26-pulp-3,
See: https://pulp.plan.io/issues/3318
=> Let dev playbook target all hosts

ansible/roles/dev/tasks/main.yml, ansible/roles/plugin/tasks/main.yml
`include` is deprecated and it's future is uncertain. We should remove it.
See http://docs.ansible.com/ansible/latest/include_module.html#deprecated.
=> Remove the use of include

ansible/pulp-from-source.yml, ansible/roles/broker/tasks/main.yml, ansible/roles/db/tasks/main.yml, ansible/roles/dev/handlers/main.yml, ansible/roles/dev/tasks/main.yml, ansible/roles/dev_tools/tasks/main.yml, ansible/roles/django_db/tasks/makemigrations.yml, ansible/roles/django_db/tasks/reset.yml, ansible/roles/kombu_fixup/tasks/main.yml, ansible/roles/lazy/tasks/main.yml, ansible/roles/plugin/tasks/main.yml, ansible/roles/pulp-user/tasks/main.yml, ansible/roles/systemd/tasks/main.yml
Don't assume that Ansible logs in as a user called "vagrant." Instead,
assume that Ansible logs in as some user that has sudo access. This
makes non-Vagrant dev environments work better. And it's good practice
anyway!
See: https://pulp.plan.io/issues/3318
=> Don't assume that Ansible logs in as vagrant user

ansible/pulp-from-source.yml, ansible/roles/pulp-user/tasks/main.yml
Ansible 2.4 or newer is required to use the new `include_*` and
`import_*` statements. See: 4a01ead42270453b6ba17a7cea339685d1a2ee24
Also, move this check into the root playbook. This allows the following
roles to be re-ordered and re-written in crazy ways, without worrying
about losing this important pre-flight check.
=> Require Ansible 2.4+

ansible/roles/dev/tasks/main.yml, ansible/roles/django_db/README.md, ansible/roles/django_db/tasks/main.yml, ansible/roles/django_db/tasks/makemigrations.yml, ansible/roles/django_db/tasks/reset.yml, ansible/roles/plugin/tasks/main.yml
The `django_db` role has two task files, neither of which is named
`main.yml`. This makes role invocation verbose and repetitive:
```yaml
- name: Make migrations for {{ pulp_app }}
include_role:
name: django_db
tasks_from: makemigrations
vars:
app_label: pulp_app
- name: Run migrations
include_role:
name: django_db
tasks_from: reset
```
Simplify the role, so that it can be invoked like so:
```yaml
- name: Make and run migrations for {{ pulp_app }}
include_role:
name: django_db
vars:
app_label: pulp_app
```
This is much more concise, and it works well for all current use cases.
It has a downside: If a caller wants to create several migrations and
run them all in one go, then this role doesn't allow for that. If this
situation arises, though, it can be addressed by letting the role accept …
=> Simplify django_db role

ansible/roles/dev/tasks/main.yml
The `dbshell` command wasn't working because it requires the binary
client. This will ensure that on dev installs at least that will work.
https://pulp.plan.io/issues/3359
re #3359
=> Adding sqlite binary to dev env

ansible/pulp-from-source.yml
Leaving commented-out code lying around is messy:
* Commented-out code distracts from the actual, working code.
* If someone needs to know how to write a playbook, they can look at the
Ansible documentation, or existing code in `pulp-from-source.yml` or
`deploy-pulp3.yml`.
* If someone needs to know the past state of this playbook, they can use
git.
=> Drop commented-out code

.travis.yml, ansible/roles/dev/tasks/main.yml, ansible/roles/dev_tools/tasks/main.yml, ansible/roles/plugin/tasks/main.yml
The first commit fixes all remaining warnings emitted by ansible-lint. The second adds a `.travis.yml`.
=> Fix linting issues, enable Travis checks

ansible/library/pulp_facts.py
The spec files were recently removed from the repos of all of the
plugins which breaks the pulp2 dev env that would inspect them. This is
a hard-list of the dependencies and will allow the dev env to continue
working.
There is not an issue associated with the spec file change so this PR
also does not have an issue.
=> Specify all rpm deps

ansible/deploy-pulp3.yml
`group_vars/all` already declared `ansible_python_interpreter`. Don't
declare it again in the `deploy-pulp3.yml` playbook.
=> Drop redundant variable declaration

ansible/pulp-from-source.yml, ansible/roles/dev_tools/tasks/main.yml
When installing packages, assert that necessary packages are "present,"
not "latest." The justification for installing the latest versions of
packages is that the devs want to know if Pulp 3 works with the latest
packages. However:
* Upgrading to the latest versions of packages makes the install take
longer.
* Upgrading to the latest versions of packages makes installs
non-idempotent.
* If a dev wants an up-to-date set of packages, it's as easy as logging
in and executing `dnf -y update`. And the developers are likely to
start building fresh Vagrant images daily in the near future.
=> Don't install "latest" version of packages

ansible/roles/kombu_fixup/tasks/main.yml
python-qpid-proton depends on redhat-rpm-config on Fedora cloud images.
closes #3468
https://pulp.plan.io/issues/3468
=> Install dep for python-qpid-proton on Fedora cloud

ansible/pulp-from-source.yml
It's entirely possible to install Pulp 3 on a host for which the
`ansible_python_interpreter` is older than Python 3.5. What matters is
that Python 3.5+ can be made available. For example, on
RHEL 7, the default Python interpreter is Python 2.7, but Python 3.5 can
be installed via an SCL, and Pulp can be installed into a virtualenv
that uses the SCL Python.
=> Don't require Python 3.5+

ansible/configure-rhel-7.yml, ansible/group_vars/all, ansible/pulp-from-source.yml, ansible/roles/configure_rhel_7/README.md, ansible/roles/configure_rhel_7/tasks/main.yml, ansible/roles/db/tasks/main.yml, ansible/roles/dev/tasks/main.yml, ansible/roles/django_db/tasks/main.yml, ansible/roles/kombu_fixup/tasks/main.yml, ansible/roles/plugin/tasks/main.yml, ansible/roles/systemd/templates/pulp_resource_manager.j2, ansible/roles/systemd/templates/pulp_worker@.j2
Add a new playbook, `configure-rhel-7.yml`, which takes care of
pre-installation tasks, like calling subscription-manager and enabling
the appropriate repositories.
Re-jigger all of the roles called by `pulp-from-source.yml`, so that
they can target either Fedora or RHEL 7. Notably, this required adding a
`pulp_python_interpreter` variable. This variable defaults to
`/usr/bin/python3` on Fedora and `/usr/bin/scl enable rh-python36 --
python3` on RHEL. Many Python invocations needed to be updated to take
this change in to account. The references to SCL are necessary because
the Python 3 provided by the standard repositories is version 3.4, but
Pulp 3 requires Python 3.5+.
The development environment doesn't totally work on RHEL 7. Certain
automatically-executed Bash scripts need to be …
=> Support Pulp 3 on RHEL 7

ansible/roles/pulp-user/tasks/main.yml
When running ansible locally (for pulp_ansible) it refuses to run
saying:  ~/.netrc access too permissive: and then refusing to install
anything on the system.
This fixes the perms to 0600 which fixed the problem for my local
environment.
=> Set .netrc to owner perms only

Vagrantfile.example, ansible/pulp-from-source.yml
An deadlock issue with Pulp's cancellation has been discovered with the
Qpid/kombu code. We can still test the Qpid stack as that resolves, but
we shouldn't default into a known-broken environment.
=> Switches default broker to RabbitMQ

ansible/roles/dev/tasks/main.yml
This reverts commit fe68c0a850ffe0d7361ae5956bebdc5ac886fe9b.
fixes #3505
https://pulp.plan.io/issues/3505
=> Revert "Adding sqlite binary to dev env"

scripts/vagrant-setup.sh
`psmash` tooling fails to run correctly with the workflow below (which I'm told is legit!).
* Missing Python development dependencies from the pulp-smash.
* Missing attrs commands (getfattr). Yum dependencies are missing.
* Many "Name or service not found due" to incorrect hostname in settings produced by vagrant-setup.sh.
```
[laptop] $ mkdir ~/pulp-devel
[laptop] $ pushd ~/pulp-devel
[laptop] $ git clone git@github.com:pulp/devel.git
[laptop] $ git clone git@github.com:pulp/pulp.git
[laptop] $ git clone git@github.com:PulpQE/pulp-smash.git
[laptop] $ pushd devel
[laptop] $ vagrant up --provider=docker
[laptop] $ vagrant ssh
[vagrant@pulp2] $ psmash
```
After setting up a clean workspace, psmash doesn't work.
```
[vagrant@pulp2 ~]$ psmash
~ ~/devel/pulp-smash
flake8 . --ignore E501,F401 …
```
=> WIP: Fix issues in vagrant's provisioning of pulp-smash

scripts/vagrant-setup.sh
Per PulpQE/pulp-smash#975.
The default behavior is to already have selinux tests enabled. This merely makes the default deploy of the config present it as a hint to the future.
=> Rename pulp selinux enabled flag

ansible/library/pulp_facts.py, scripts/bootstrap-ansible.sh
python-django -> python2-django1.11
python-rhsm was removed, and has not yet been replaced in the upstream
repo. Instead, I added url installs to the pre-script.
=> Update packages to match fedora repo

.travis.yml
Ansible-lint checks for code smells, not syntax issues. Thus, it's
useful to call both ansible-lint and Ansible's syntax checker.
=> Make Travis check syntax of pulp-from-source.yml

ansible/pulp-from-source.yml, ansible/roles/dev/tasks/main.yml, ansible/roles/django_db/tasks/main.yml, ansible/roles/plugin/tasks/main.yml
Problem 1:  Re-running the ansible playbook on a box with an existing Pulp installation fails because the workers have active database connections, therefore it fails when attempting to reset the db.
Problem 2:  The ```django_db``` role is run for every single plugin, resetting the database and running the migrations over and over.  Apart from being inefficient, this seems to occasionally cause problems: https://pulp.plan.io/issues/3739
* Stop the systemd services prior to doing db reset / migration steps, and restart them after.  If it can't find the services because they haven't been installed yet, ignore them.
* Let the ```plugin``` role worry about *making* the migrations, and the ```django_db``` role worry about running them.  Only run ```django_db``` role once.
=> Revamp how ansible does migrations

ansible/roles/dev/tasks/main.yml
When ansible executes tasks on a remote system, it executes those tasks
as the user it has logged in as. This behaviour can be overridden by
specifying task arguments such as `become: true`.
When Pulp 3 is being installed, migrations must be created for each of
the Django applications that comprise Pulp 3. When migrations are
created for the `pulp_app`, a permission denial occurs, because they are
being created as the default Ansible user. Fix this error by creating
migrations for `pulp_app` as root.
See: 4aa6fd29d8fa422ee01b475f387557a9a534f488
=> Create permissions for pulp_app as root

Vagrantfile.example, ansible/library/pulp_facts.py
This goes hand in hand with:
https://github.com/pulp/pulp_deb/pull/45
Together they make spinning up the pulp2_dev vagrant box with pulp_deb possible again.
=> Fix pulp_deb dependencies

ansible/roles/dev/tasks/main.yml, ansible/roles/dev_tools/tasks/main.yml
* Install jemalloc-devel which Redis needs when starting on f28 for some
reason.
* Remove the custom RQ version we were using
* Skip errors on a place that was halting the playbook even though it
has correct error checking.
=> Small devel fixes

Vagrantfile.example, docker/Dockerfile
The vagrant user is created with a default user EUID/EGID[1]
This prevets the RW access if vagrant user EUID isn't the same as the host user EUID.
Since the uid of a user can't be changed while it has any running processes (ssh) ansible can't be used to update the euid.
The patch introduces Dockerfile that modifies the vagrant EUID/EGID build-time.
Closes: #176
[1] https://github.com/rohanpm/docker-fedora-vagrant/blob/master/Dockerfile#L30
=> usermod vagrant with host user euid

Vagrantfile.example, ansible/roles/django_db/tasks/main.yml
- don't use GID on OSX as it fails provision
- fix ansible-lint in travis by ignoring ANSIBLE0012 in djangodb migration task
Signed-off-by: Pavel Picka <ppicka@redhat.com>
=> OSX Vagrantfile

ansible/roles/dev/tasks/main.yml, ansible/roles/pulp-user/templates/alias.bashrc
pulpcore.common was removed and now is just part of the pulpcore
package. As such the install fails now. This removes that from the dev
install so it can start working again.
https://pulp.plan.io/issues/3652
re: #3652
=> The common package was removed

ansible/pulp-from-source.yml, ansible/roles/plugin/tasks/install_plugin.yml, ansible/roles/plugin/tasks/main.yml
I am not sure, whether those playbooks are used elsewhere, but if you want to mimic the way, the vagrant dev environment included the pulp plugins, this might be the way.
=> RFC: Install plugins in dev-environment if available

ansible/roles/dev/tasks/main.yml
For some reason installing both of them at the same time caused them to
be resolved from pypi instead of from the setup.py
https://pulp.plan.io/issues/4135
closes #4135
=> Fixes installs to be from source

ansible/pulp-from-source.yml, ansible/roles/createrepo_c/tasks/main.yml
Avoids provisioning failure when pulp_rpm is one of the plugins to be installed.
=> Add a temporary? role for createrepo_c build dependencies

ansible/roles/dev/tasks/main.yml, docker/Dockerfile, scripts/bootstrap-ansible.sh
- We shouldn't be using fedora:latest. It can change to a newer
major version at any time, breaking the dev env.
Right now, fedora:latest is 29 and that's broken since nightly
repos aren't generated for F29 yet[1].
Also, the libvirt provider for the dev-env uses F28. It seems
a good idea for the libvirt and docker providers to be using
the same major version of fedora.
- The hack for installing subscription manager doesn't seem needed
any more, F28 has both subscription-manager-rhsm-certificates
and python2-subscription-manager-rhsm
- Install dnf-utils rather than yum-utils because, on later Fedora,
dnf-utils and yum-utils conflict.
[1] https://repos.fedorapeople.org/repos/pulp/pulp/testing/automation/2-master/stage/
=> Fix docker dev env provision
